const PRODUCTS=window.PRODUCTS; const WA='18296480491'; const CDN={"MUJ-001":"https://cdn.shopify.com/s/files/1/0853/6909/4364/files/MUJ-001-original.jpg?v=1789576938","MUJ-002":"https://cdn.shopify.com/s/files/1/0853/6909/4364/files/MUJ-002-original.jpg?v=1789576948","MUJ-003":"https://cdn.shopify.com/s/files/1/0853/6909/4364/files/MUJ-003-original.jpg?v=1789576959","MUJ-004":"https://cdn.shopify.com/s/files/1/0853/6909/4364/files/MUJ-004-original.jpg?v=1789576973","MUJ-005":"https://cdn.shopify.com/s/files/1/0853/6909/4364/files/MUJ-005-original.jpg?v=1789576985","MUJ-006":"https://cdn.shopify.com/s/files/1/0853/6909/4364/files/MUJ-006-original.jpg?v=1789577006","MUJ-007":"https://cdn.shopify.com/s/files/1/0853/6909/4364/files/MUJ-007-original.jpg?v=1789577015","MUJ-008":"https://cdn.shopify.com/s/files/1/0853/6909/4364/files/MUJ-008-original.jpg?v=1789577028"}; let filter='Todos'; let cart=JSON.parse(localStorage.getItem('kopyr_cart_premium')||'[]');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; const money=v=>'RD$'+Number(v||0).toLocaleString('es-DO');
function drive(id){return id?`https://drive.google.com/thumbnail?id=${id}&sz=w2000`:''}
function sources(p){let a=[];if(CDN[p.sku])a.push(CDN[p.sku]);if(p.orig&&p.orig.length)a.push(...p.orig.map(drive));if(p.edit)a.push(drive(p.edit));return [...new Set(a.filter(Boolean))]}
function image(p){return sources(p)[0]||''}
function nextImage(el,sku){let p=PRODUCTS.find(x=>x.sku===sku);if(!p){el.style.display='none';return}let a=sources(p),i=Number(el.dataset.i||0)+1;el.dataset.i=i;if(i<a.length)el.src=a[i];else el.style.display='none'}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1400)}
function setFilter(f){filter=f; $$('.f').forEach(b=>b.classList.toggle('on',b.dataset.f===f)); render(); setTimeout(()=>$('#tienda').scrollIntoView({behavior:'smooth'}),80)}
function focusCatalog(){$('#tienda').scrollIntoView({behavior:'smooth'});setTimeout(()=>$('#searchTop').focus(),400)}
function q(){return ($('#searchTop').value||$('#searchMobile').value||'').trim().toLowerCase()}
function list(){let a=PRODUCTS.filter(p=>(filter==='Todos'||(filter==='150'?p.price<=150:p.category===filter))&&(!q()||p.search.includes(q())));let s=$('#sort').value;if(s==='low')a.sort((a,b)=>a.price-b.price);if(s==='high')a.sort((a,b)=>b.price-a.price);if(s==='az')a.sort((a,b)=>a.name.localeCompare(b.name,'es'));return a}
function cartItem(sku){return cart.find(x=>x.sku===sku)}
function render(){let a=list();$('#count').textContent=a.length;$('#countLine').textContent=`Mostrando ${a.length} productos`;$('#grid').innerHTML=a.map((p,idx)=>{let c=cartItem(p.sku);let meta=[p.brand,p.size].filter(Boolean).join(' · ');let sale=p.price<=150;return `<article class="card"><div class="imageBox" onclick="openZoom('${p.sku}')"><img src="${image(p)}" data-i="0" alt="${p.name}" loading="${idx<8?'eager':'lazy'}" ${idx<4?'fetchpriority="high"':''} onerror="nextImage(this,'${p.sku}')"><span class="badge ${sale?'sale':''}">${sale?'OFERTA':p.category}</span><button class="buyNow" onclick="event.stopPropagation();buyNow('${p.sku}')">Comprar ahora</button></div><div class="pbody"><div class="brandLine">${p.brand||p.category}</div><div class="pname">${p.name}</div><div class="meta">${meta||p.color||p.sub}</div><div class="priceRow"><span class="price">${money(p.price)}</span>${sale?'<span class="chip">precio fácil</span>':''}<button class="add" onclick="toggle('${p.sku}')">${c?'✓':'+'}</button></div></div></article>`}).join('');renderCart()}
function save(){localStorage.setItem('kopyr_cart_premium',JSON.stringify(cart))}
function toggle(sku){let i=cart.findIndex(x=>x.sku===sku);if(i>=0){cart.splice(i,1);toast('Producto eliminado')}else{cart.push({sku,qty:1});toast('Agregado al carrito')}save();render()}
function buyNow(sku){if(!cartItem(sku))cart.push({sku,qty:1});save();render();openCart()}
function detail(){return cart.map(c=>{let p=PRODUCTS.find(x=>x.sku===c.sku);return p?{...p,qty:c.qty,line:p.price*c.qty}:null}).filter(Boolean)}
function qty(sku,d){let c=cartItem(sku);if(!c)return;c.qty=Math.max(1,c.qty+d);save();render()} function rem(sku){cart=cart.filter(x=>x.sku!==sku);save();render()}
function renderCart(){let d=detail();$('#cartItems').innerHTML=d.length?d.map(p=>`<div class="cartItem"><div class="thumb"><img src="${image(p)}" data-i="0" onerror="nextImage(this,'${p.sku}')"></div><div><b>${p.name}</b><small>${p.sku} · ${money(p.price)}${p.size?' · '+p.size:''}</small><div class="qty"><button onclick="qty('${p.sku}',-1)">−</button><b>${p.qty}</b><button onclick="qty('${p.sku}',1)">+</button></div></div><div><b>${money(p.line)}</b><br><button class="remove" onclick="rem('${p.sku}')">Quitar</button></div></div>`).join(''):'<div style="padding:28px;text-align:center;color:#777">Tu carrito está vacío.</div>';let n=d.reduce((a,b)=>a+b.qty,0),t=d.reduce((a,b)=>a+b.line,0);$('#countTop').textContent=n;$('#stickyCount').textContent=n;$('#sumQty').textContent=n;$('#stickyTotal').textContent=money(t);$('#sumTotal').textContent=money(t)}
function openCart(){$('#drawerWrap').classList.add('open')} function closeCart(){$('#drawerWrap').classList.remove('open')} function wa(){window.open('https://wa.me/'+WA,'_blank')}
function orderText(){let d=detail();let total=d.reduce((a,b)=>a+b.line,0);let lines=d.map(p=>`• ${p.qty} x ${p.name} (${p.sku}) — ${money(p.line)}`);let pay=$('#pay').value;return ['Hola KOPYR STORE 👋','Quiero finalizar este pedido:','',...lines,'',`Total estimado: ${money(total)}`,'',`Nombre: ${$('#name').value||'Por confirmar'}`,`Teléfono: ${$('#phone').value||'Por confirmar'}`,`Ciudad / sector: ${$('#area').value||'Por confirmar'}`,`Dirección: ${$('#address').value||'Por confirmar'}`,`Método de pago: ${pay}`, $('#notes').value?`Nota: ${$('#notes').value}`:'', '', pay==='Transferencia'?'Enviaré el comprobante por este medio.':pay==='Contra entrega'?'Quiero coordinar contra entrega.':'Quiero coordinar pago y entrega por WhatsApp.'].filter(Boolean).join('\n')}
function openZoom(sku){let p=PRODUCTS.find(x=>x.sku===sku);if(!p)return;let z=$('#zoomImg');z.dataset.i='0';z.dataset.sku=sku;z.src=image(p);z.onerror=()=>nextImage(z,sku);$('#zoomBrand').textContent=p.brand||p.category;$('#zoomName').textContent=p.name;$('#zoomMeta').textContent=[p.size,p.color,p.sku].filter(Boolean).join(' · ');$('#zoomPrice').textContent=money(p.price);$('#zoomAdd').onclick=()=>{if(!cartItem(sku)){cart.push({sku,qty:1});save();render()}toast('Agregado al carrito')};$('#zoomBuy').onclick=()=>{closeZoom();buyNow(sku)};$('#zoomWrap').classList.add('open')}
function closeZoom(){$('#zoomWrap').classList.remove('open')}
function finishOrder(){if(!cart.length)return toast('Agrega productos al carrito');window.open('https://wa.me/'+WA+'?text='+encodeURIComponent(orderText()),'_blank')}
$$('.f').forEach(b=>b.onclick=()=>setFilter(b.dataset.f));$('#sort').onchange=render;$('#searchTop').oninput=()=>{$('#searchMobile').value=$('#searchTop').value;render()};$('#searchMobile').oninput=()=>{$('#searchTop').value=$('#searchMobile').value;render()};render();