import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Json = Record<string, unknown>;
type Job = { id:string; tenant_id:string; connection_id:string; job_type:'healthcheck'|'pull'|'push'|'reconcile'|'full_sync'; entity_type:string|null; entity_id:string|null; lock_token:string; payload:Json };
type Connection = { id:string; tenant_id:string; provider:string; base_url:string; database_name:string|null; credential_ref:string|null; status:string };
type Mapping = { id:string; erp_model:string; erp_record_id:string; last_synced_at:string|null; crm_updated_at:string|null; erp_updated_at:string|null; checksum:string|null; metadata:Json };
type CrmSnapshot = { entityType:string; id:string; updatedAt:string; values:Json; odooValues:Json };

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const WORKER_ID = `edge:odoo-sync-worker:${crypto.randomUUID()}`;
const ALLOWED_MODELS = new Set(['res.partner','product.product','sale.order']);
const ALLOWED_PULL_METHODS = new Set(['search_read','read']);

function jsonResponse(body: unknown, status=200) { return new Response(JSON.stringify(body), { status, headers:{'content-type':'application/json; charset=utf-8'} }); }
function decodeJwtPayload(token:string):Json|null { try { const p=token.split('.')[1]; if(!p) return null; const n=p.replace(/-/g,'+').replace(/_/g,'/'); return JSON.parse(atob(n+'='.repeat((4-n.length%4)%4))); } catch { return null; } }
function requireServiceRole(req:Request) { const h=req.headers.get('authorization')??''; if(!h.toLowerCase().startsWith('bearer ')) return false; return decodeJwtPayload(h.slice(7).trim())?.role==='service_role'; }
function asObject(v:unknown):Json { return v && typeof v==='object' && !Array.isArray(v) ? v as Json : {}; }
function expectedModel(entityType:string|null):string|null { switch(entityType){ case 'company': case 'contact': return 'res.partner'; case 'product': return 'product.product'; case 'quotation': return 'sale.order'; default:return null; } }
function tableForEntity(entityType:string){ switch(entityType){ case 'company':return 'companies'; case 'contact':return 'contacts'; case 'product':return 'products'; case 'quotation':return 'quotations'; default: throw Object.assign(new Error(`unsupported_entity_type:${entityType}`),{retryable:false}); } }
function parseDateMs(v:unknown){ if(typeof v!=='string') return 0; const n=Date.parse(v); return Number.isFinite(n)?n:0; }
function baseUrl(url:string){ return url.replace(/\/+$/,''); }

async function sb(path:string, init:RequestInit={}){ const headers=new Headers(init.headers); headers.set('apikey',SERVICE_KEY); headers.set('authorization',`Bearer ${SERVICE_KEY}`); headers.set('content-type','application/json'); return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers}); }
async function rpc<T>(fn:string, body:Json):Promise<T>{ const r=await sb(`rpc/${fn}`,{method:'POST',body:JSON.stringify(body)}); if(!r.ok) throw new Error(`supabase_rpc_${fn}:${r.status}:${await r.text()}`); return await r.json() as T; }
async function one<T>(path:string):Promise<T|null>{ const r=await sb(path); if(!r.ok) throw new Error(`supabase_read_failed:${r.status}:${await r.text()}`); const rows=await r.json() as T[]; return rows[0]??null; }
async function insert(path:string, body:unknown){ const r=await sb(path,{method:'POST',headers:{prefer:'return=minimal'},body:JSON.stringify(body)}); if(!r.ok) throw new Error(`supabase_insert_failed:${r.status}:${await r.text()}`); }
async function patch(path:string, body:unknown){ const r=await sb(path,{method:'PATCH',headers:{prefer:'return=minimal'},body:JSON.stringify(body)}); if(!r.ok) throw new Error(`supabase_patch_failed:${r.status}:${await r.text()}`); }

async function getConnection(job:Job):Promise<Connection>{ const p=new URLSearchParams({id:`eq.${job.connection_id}`,tenant_id:`eq.${job.tenant_id}`,select:'id,tenant_id,provider,base_url,database_name,credential_ref,status',limit:'1'}); const row=await one<Connection>(`erp_connections?${p}`); if(!row) throw new Error('connection_not_found'); if(row.provider!=='odoo') throw new Error(`unsupported_erp_provider:${row.provider}`); return row; }
async function resolveCredential(connection:Connection):Promise<string> { const ref=connection.credential_ref; if(!ref) throw new Error('missing_credential_ref'); if(ref.startsWith('vault:')){ const secret=await rpc<string>('resolve_erp_connection_credential',{p_connection_id:connection.id}); if(!secret) throw new Error('vault_credential_not_found'); return secret; } if(!ref.startsWith('env:')) throw new Error('unsupported_credential_ref_scheme'); const name=ref.slice(4); if(!/^[A-Z][A-Z0-9_]{2,127}$/.test(name)) throw new Error('invalid_credential_ref'); const secret=Deno.env.get(name); if(!secret) throw new Error(`credential_not_configured:${name}`); return secret; }
async function odooCall(connection:Connection, model:string, method:string, payload:Json){ if(!ALLOWED_MODELS.has(model)) throw new Error(`odoo_model_not_allowed:${model}`); const credential=await resolveCredential(connection); const headers=new Headers({authorization:`bearer ${credential}`,'content-type':'application/json; charset=utf-8','user-agent':'crm-saas-odoo-adapter/1.2'}); if(connection.database_name) headers.set('x-odoo-database',connection.database_name); const r=await fetch(`${baseUrl(connection.base_url)}/json/2/${model}/${method}`,{method:'POST',headers,body:JSON.stringify(payload)}); const text=await r.text(); let data:unknown=text; try{data=text?JSON.parse(text):null}catch{} if(!r.ok){const e=new Error(`odoo_http_${r.status}`) as Error & {retryable?:boolean;details?:unknown}; e.retryable=r.status===408||r.status===425||r.status===429||r.status>=500;e.details=data;throw e;} return data; }
async function updateConnectionHealth(c:Connection, ok:boolean, error:string|null){ const p=new URLSearchParams({id:`eq.${c.id}`,tenant_id:`eq.${c.tenant_id}`}); await patch(`erp_connections?${p}`,{status:ok?'connected':'error',last_healthcheck_at:new Date().toISOString(),last_error:error,updated_at:new Date().toISOString()}); }
async function healthcheck(c:Connection){ const r=await fetch(`${baseUrl(c.base_url)}/web/version`,{headers:{'user-agent':'crm-saas-odoo-adapter/1.1'}}); if(!r.ok){await updateConnectionHealth(c,false,`HTTP ${r.status}`); const e=new Error(`odoo_healthcheck_http_${r.status}`) as Error & {retryable?:boolean}; e.retryable=r.status===408||r.status===425||r.status===429||r.status>=500; throw e;} const version=await r.json(); await updateConnectionHealth(c,true,null); return {ok:true,version}; }

async function findMapping(job:Job):Promise<Mapping|null>{ if(!job.entity_type||!job.entity_id)return null; const p=new URLSearchParams({tenant_id:`eq.${job.tenant_id}`,connection_id:`eq.${job.connection_id}`,crm_entity_type:`eq.${job.entity_type}`,crm_entity_id:`eq.${job.entity_id}`,select:'id,erp_model,erp_record_id,last_synced_at,crm_updated_at,erp_updated_at,checksum,metadata',limit:'1'}); return await one<Mapping>(`erp_entity_mappings?${p}`); }
async function findRelatedMapping(tenantId:string,connectionId:string,entityType:string,entityId:string){ const p=new URLSearchParams({tenant_id:`eq.${tenantId}`,connection_id:`eq.${connectionId}`,crm_entity_type:`eq.${entityType}`,crm_entity_id:`eq.${entityId}`,select:'erp_record_id,erp_model',limit:'1'}); return await one<{erp_record_id:string;erp_model:string}>(`erp_entity_mappings?${p}`); }
async function upsertMapping(job:Job,model:string,recordId:string,crmUpdatedAt:string|null,erpUpdatedAt:string|null,checksum:string|null,metadata:Json={}){ if(!job.entity_type||!job.entity_id)return; const body={tenant_id:job.tenant_id,connection_id:job.connection_id,crm_entity_type:job.entity_type,crm_entity_id:job.entity_id,erp_model:model,erp_record_id:recordId,sync_status:'synced',crm_updated_at:crmUpdatedAt,erp_updated_at:erpUpdatedAt,last_synced_at:new Date().toISOString(),checksum,metadata,updated_at:new Date().toISOString()}; const r=await sb('erp_entity_mappings?on_conflict=connection_id,crm_entity_type,crm_entity_id',{method:'POST',headers:{prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(body)}); if(!r.ok) throw new Error(`mapping_upsert_failed:${r.status}:${await r.text()}`); }

async function loadCrmRow(job:Job):Promise<Json>{ if(!job.entity_type||!job.entity_id) throw new Error('entity_required'); const table=tableForEntity(job.entity_type); const p=new URLSearchParams({id:`eq.${job.entity_id}`,tenant_id:`eq.${job.tenant_id}`,select:'*',limit:'1'}); const row=await one<Json>(`${table}?${p}`); if(!row) throw Object.assign(new Error('crm_entity_not_found'),{retryable:false}); return row; }
async function loadQuotationItems(job:Job){ const p=new URLSearchParams({quotation_id:`eq.${job.entity_id}`,tenant_id:`eq.${job.tenant_id}`,select:'id,product_id,description,quantity,unit_price,discount_percent,tax_rate,position',order:'position.asc'}); const r=await sb(`quotation_items?${p}`); if(!r.ok) throw new Error(`quotation_items_lookup_failed:${r.status}:${await r.text()}`); return await r.json() as Json[]; }

async function buildSnapshot(job:Job):Promise<CrmSnapshot>{ const row=await loadCrmRow(job); const entityType=job.entity_type!; const id=String(row.id); const updatedAt=String(row.updated_at??''); let odooValues:Json={};
  if(entityType==='company'){ odooValues={name:row.name,email:row.email??false,phone:row.phone??false,website:row.domain??false,is_company:true,company_type:'company'}; }
  else if(entityType==='contact'){ const vals:Json={name:row.display_name,email:row.email??false,phone:row.phone??false,is_company:false,company_type:'person'}; if(row.company_id){ const m=await findRelatedMapping(job.tenant_id,job.connection_id,'company',String(row.company_id)); if(m?.erp_record_id) vals.parent_id=Number(m.erp_record_id); } odooValues=vals; }
  else if(entityType==='product'){ odooValues={name:row.name,default_code:row.sku,description_sale:row.description??false,list_price:Number(row.sale_price??0),active:row.status==='active'}; }
  else if(entityType==='quotation'){ let partnerId:number|undefined; if(row.contact_id){ const m=await findRelatedMapping(job.tenant_id,job.connection_id,'contact',String(row.contact_id)); if(m?.erp_record_id) partnerId=Number(m.erp_record_id); } if(!partnerId&&row.company_id){ const m=await findRelatedMapping(job.tenant_id,job.connection_id,'company',String(row.company_id)); if(m?.erp_record_id) partnerId=Number(m.erp_record_id); } if(!partnerId) throw Object.assign(new Error('quotation_requires_mapped_partner'),{retryable:false}); const items=await loadQuotationItems(job); const orderLine:unknown[]=[]; for(const item of items){ if(!item.product_id) throw Object.assign(new Error('quotation_item_requires_product'),{retryable:false}); const pm=await findRelatedMapping(job.tenant_id,job.connection_id,'product',String(item.product_id)); if(!pm?.erp_record_id) throw Object.assign(new Error(`quotation_product_not_mapped:${item.product_id}`),{retryable:false}); orderLine.push([0,0,{product_id:Number(pm.erp_record_id),name:item.description,product_uom_qty:Number(item.quantity??1),price_unit:Number(item.unit_price??0),discount:Number(item.discount_percent??0)}]); } odooValues={partner_id:partnerId,client_order_ref:row.quote_number,validity_date:row.valid_until??false,note:[row.notes,row.terms].filter(Boolean).join('\n\n')||false,order_line:orderLine}; }
  return {entityType,id,updatedAt,values:row,odooValues}; }

function canonical(value:unknown):string { if(Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; if(value&&typeof value==='object'){const o=value as Json; return `{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${canonical(o[k])}`).join(',')}}`;} return JSON.stringify(value); }
async function sha256(value:unknown){ const bytes=new TextEncoder().encode(canonical(value)); const hash=await crypto.subtle.digest('SHA-256',bytes); return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
async function readOdooState(c:Connection,model:string,id:number){ const result=await odooCall(c,model,'read',{ids:[id],fields:['id','write_date','name']}); return Array.isArray(result)?asObject(result[0]):{}; }
async function logEvent(job:Job,direction:'inbound'|'outbound'|'internal',eventType:string,status:'info'|'success'|'warning'|'error',details:Json,model?:string,recordId?:string){ await insert('erp_sync_events',{tenant_id:job.tenant_id,connection_id:job.connection_id,job_id:job.id,direction,event_type:eventType,entity_type:job.entity_type,crm_entity_id:job.entity_id,erp_model:model??null,erp_record_id:recordId??null,status,details}); }
async function createConflict(job:Job,mapping:Mapping,snapshot:CrmSnapshot,erpSnapshot:Json){ try { await insert('erp_sync_conflicts',{tenant_id:job.tenant_id,connection_id:job.connection_id,mapping_id:mapping.id,job_id:job.id,entity_type:job.entity_type,crm_entity_id:job.entity_id,erp_model:mapping.erp_model,erp_record_id:mapping.erp_record_id,conflict_type:'concurrent_update',status:'open',crm_snapshot:snapshot.values,erp_snapshot:erpSnapshot}); } catch(e){ if(!String(e).includes('23505')) throw e; } const p=new URLSearchParams({id:`eq.${mapping.id}`,tenant_id:`eq.${job.tenant_id}`}); await patch(`erp_entity_mappings?${p}`,{sync_status:'conflict',updated_at:new Date().toISOString()}); await logEvent(job,'internal','sync_conflict','warning',{reason:'concurrent_update'},mapping.erp_model,mapping.erp_record_id); }

async function processPush(job:Job,c:Connection,opts:{force?:boolean}={} ){ const model=expectedModel(job.entity_type); if(!model) throw Object.assign(new Error(`unsupported_entity_type:${job.entity_type??'null'}`),{retryable:false}); const snapshot=await buildSnapshot(job); const override=asObject(job.payload).odoo_values; const values=Object.keys(override).length?override:snapshot.odooValues; const mapping=await findMapping(job); if(mapping?.erp_model&&mapping.erp_model!==model) throw Object.assign(new Error('mapping_model_mismatch'),{retryable:false}); let id:number|undefined; let erpState:Json={}; if(mapping?.erp_record_id){ id=Number(mapping.erp_record_id); if(!Number.isInteger(id)||id<=0) throw new Error('invalid_mapped_odoo_record_id'); erpState=await readOdooState(c,model,id); if(!opts.force){ const baselineCrm=parseDateMs(mapping.crm_updated_at??mapping.last_synced_at); const baselineErp=parseDateMs(mapping.erp_updated_at??mapping.last_synced_at); const crmChanged=parseDateMs(snapshot.updatedAt)>baselineCrm; const erpChanged=parseDateMs(erpState.write_date)>baselineErp; if(crmChanged&&erpChanged){ await createConflict(job,mapping,snapshot,erpState); throw Object.assign(new Error('concurrent_update'),{retryable:false}); } } await odooCall(c,model,'write',{ids:[id],vals:values}); } else { const created=await odooCall(c,model,'create',{vals_list:[values]}); const createdId=Array.isArray(created)?created[0]:created; id=Number(createdId); if(!Number.isInteger(id)||id<=0) throw new Error('odoo_create_returned_invalid_id'); }
  const post=await readOdooState(c,model,id!); const checksum=await sha256(snapshot.values); await upsertMapping(job,model,String(id),snapshot.updatedAt,typeof post.write_date==='string'?post.write_date:null,checksum,{last_direction:'crm_to_erp'}); await logEvent(job,'outbound','sync_succeeded','success',{operation:mapping?'update':'create',checksum},model,String(id)); return {operation:mapping?'update':'create',model,erp_record_id:id,checksum}; }

async function processPull(job:Job,c:Connection){ const requested=String(job.payload?.odoo_model??expectedModel(job.entity_type)??''); if(!ALLOWED_MODELS.has(requested)) throw new Error(`odoo_model_not_allowed:${requested}`); const method=String(job.payload?.method??'search_read'); if(!ALLOWED_PULL_METHODS.has(method)) throw new Error(`odoo_pull_method_not_allowed:${method}`); if(method==='read'){ const ids=Array.isArray(job.payload?.ids)?job.payload.ids:[]; return await odooCall(c,requested,'read',{ids,fields:Array.isArray(job.payload?.fields)?job.payload.fields:undefined,context:typeof job.payload?.context==='object'?job.payload.context:undefined}); } return await odooCall(c,requested,'search_read',{domain:Array.isArray(job.payload?.domain)?job.payload.domain:[],fields:Array.isArray(job.payload?.fields)?job.payload.fields:undefined,limit:Math.min(Number(job.payload?.limit??100),500),offset:Math.max(Number(job.payload?.offset??0),0),order:typeof job.payload?.order==='string'?job.payload.order:undefined,context:typeof job.payload?.context==='object'?job.payload.context:undefined}); }

async function processReconcile(job:Job,c:Connection){ const conflictId=String(job.payload?.conflict_id??''); const strategy=String(job.payload?.resolution_strategy??''); if(!conflictId||!['crm_wins','ignore'].includes(strategy)) throw Object.assign(new Error('reconcile_supports_crm_wins_or_ignore'),{retryable:false}); const p=new URLSearchParams({id:`eq.${conflictId}`,tenant_id:`eq.${job.tenant_id}`,connection_id:`eq.${job.connection_id}`,select:'*',limit:'1'}); const conflict=await one<Json>(`erp_sync_conflicts?${p}`); if(!conflict) throw Object.assign(new Error('conflict_not_found'),{retryable:false}); if(!['open','resolving'].includes(String(conflict.status))) throw Object.assign(new Error('conflict_not_active'),{retryable:false}); await patch(`erp_sync_conflicts?id=eq.${conflictId}&tenant_id=eq.${job.tenant_id}`,{status:'resolving',resolution_strategy:strategy,updated_at:new Date().toISOString()}); if(strategy==='ignore'){ await patch(`erp_sync_conflicts?id=eq.${conflictId}&tenant_id=eq.${job.tenant_id}`,{status:'ignored',resolved_at:new Date().toISOString(),resolution_details:{reason:'explicit_ignore'},updated_at:new Date().toISOString()}); await logEvent(job,'internal','conflict_ignored','warning',{conflict_id:conflictId}); return {conflict_id:conflictId,status:'ignored'}; }
  const synthetic:Job={...job,job_type:'push',entity_type:String(conflict.entity_type),entity_id:String(conflict.crm_entity_id),payload:{}}; const result=await processPush(synthetic,c,{force:true}); await patch(`erp_sync_conflicts?id=eq.${conflictId}&tenant_id=eq.${job.tenant_id}`,{status:'resolved',resolution_strategy:'crm_wins',resolved_at:new Date().toISOString(),resolution_details:{result},updated_at:new Date().toISOString()}); await logEvent(job,'internal','conflict_resolved','success',{conflict_id:conflictId,strategy:'crm_wins'}); return {conflict_id:conflictId,status:'resolved',strategy:'crm_wins',result}; }

async function processJob(job:Job){ const c=await getConnection(job); switch(job.job_type){ case 'healthcheck':return await healthcheck(c); case 'push':return await processPush(job,c); case 'pull':return await processPull(job,c); case 'reconcile':return await processReconcile(job,c); case 'full_sync':throw Object.assign(new Error('full_sync_requires_pagination_and_entity_scope'),{retryable:false}); default:throw Object.assign(new Error(`unsupported_job_type:${job.job_type}`),{retryable:false}); } }
function classifyError(error:unknown){ const e=error as Error & {retryable?:boolean;details?:unknown}; const message=e?.message||'unknown_error'; const retryable=e?.retryable??/timeout|network|fetch|429|5\d\d/i.test(message); let code=message.split(':')[0].slice(0,120).replace(/[^a-zA-Z0-9_\-]/g,'_'); if(!code) code='odoo_sync_error'; return {message,code,retryable,details:e?.details??null}; }

Deno.serve(async(req)=>{ if(req.method!=='POST')return jsonResponse({error:'method_not_allowed'},405); if(!requireServiceRole(req))return jsonResponse({error:'forbidden',detail:'service_role_required'},403); let input:Json={}; try{input=await req.json()}catch{} const limit=Math.min(Math.max(Number(input.limit??10),1),25); const leaseSeconds=Math.min(Math.max(Number(input.lease_seconds??180),30),900); try{ const jobs=await rpc<Job[]>('claim_erp_sync_jobs',{p_worker_id:WORKER_ID,p_limit:limit,p_lease_seconds:leaseSeconds}); const outcomes:Json[]=[]; for(const job of jobs){ try{const result=await processJob(job); await rpc('finish_erp_sync_job',{p_job_id:job.id,p_lock_token:job.lock_token,p_success:true,p_result:result as Json,p_error_message:null,p_failure_code:null,p_retryable:false}); outcomes.push({job_id:job.id,status:'succeeded'});}catch(error){const f=classifyError(error); try{await logEvent(job,'internal','sync_failed',f.retryable?'warning':'error',{code:f.code,message:f.message});}catch{} try{await rpc('finish_erp_sync_job',{p_job_id:job.id,p_lock_token:job.lock_token,p_success:false,p_result:f.details?{details:f.details}:null,p_error_message:f.message,p_failure_code:f.code,p_retryable:f.retryable});}catch(fe){outcomes.push({job_id:job.id,status:'finish_failed',error:String(fe)});continue;} outcomes.push({job_id:job.id,status:f.retryable?'retry_scheduled':'failed',error:f.code});} } return jsonResponse({claimed:jobs.length,outcomes}); }catch(error){console.error(error);return jsonResponse({error:'worker_failed',detail:String(error)},500);} });
