"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

type Activity={id:string;opportunity_id:string|null;contact_id:string|null;type:string;title:string;description:string|null;completed_at:string|null;assigned_to:string|null;created_at:string};
type Opportunity={id:string;title:string;contact_id:string|null;owner_user_id:string|null};

export default function CrmActivities(){
 const [tenantId,setTenantId]=useState<string|null>(null); const [rows,setRows]=useState<Activity[]>([]); const [opps,setOpps]=useState<Opportunity[]>([]); const [opportunityId,setOpportunityId]=useState(""); const [type,setType]=useState("call"); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [completed,setCompleted]=useState(true); const [notice,setNotice]=useState(""); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session?.user){location.href="/login";return}const active=await supabase.rpc("list_my_tenants");if(active.error){setNotice(active.error.message);setLoading(false);return}const memberships=(active.data??[]) as Array<{tenant_id:string;is_active:boolean}>;const chosen=memberships.find(x=>x.is_active)??memberships[0];if(!chosen){setNotice("No hay tenant activo.");setLoading(false);return}setTenantId(chosen.tenant_id)})()},[]);
 async function load(id:string){setLoading(true);const [a,o]=await Promise.all([supabase.from("activities").select("id,opportunity_id,contact_id,type,title,description,completed_at,assigned_to,created_at").eq("tenant_id",id).order("created_at",{ascending:false}).limit(500),supabase.from("opportunities").select("id,title,contact_id,owner_user_id").eq("tenant_id",id).order("updated_at",{ascending:false}).limit(1000)]);const err=a.error??o.error;if(err)setNotice(err.message);setRows((a.data??[]) as Activity[]);setOpps((o.data??[]) as Opportunity[]);setLoading(false)}
 useEffect(()=>{if(tenantId)load(tenantId)},[tenantId]);
 const opportunityMap=useMemo(()=>new Map(opps.map(o=>[o.id,o.title])),[opps]);
 async function add(e:FormEvent){e.preventDefault();if(!tenantId)return;setNotice("");const opportunity=opps.find(o=>o.id===opportunityId);const completedAt=completed?new Date().toISOString():null;const r=await supabase.from("activities").insert({tenant_id:tenantId,opportunity_id:opportunityId||null,contact_id:opportunity?.contact_id??null,type,title,description:description||null,completed_at:completedAt,assigned_to:opportunity?.owner_user_id??null});if(r.error){setNotice(r.error.message);return}if(opportunityId&&completedAt){const u=await supabase.from("opportunities").update({last_activity_at:completedAt}).eq("tenant_id",tenantId).eq("id",opportunityId);if(u.error){setNotice("Actividad registrada; no se pudo actualizar la última actividad: "+u.error.message);await load(tenantId);return}}setOpportunityId("");setTitle("");setDescription("");setCompleted(true);setNotice("Actividad registrada.");await load(tenantId)}
 const date=new Intl.DateTimeFormat("es-DO",{dateStyle:"medium",timeStyle:"short"});
 return <div className="stack gap-16"><header><div className="eyebrow">CRM 360° · Actividades</div><h1>Actividad y resultado comercial</h1></header>{notice&&<div className="notice">{notice}</div>}<form className="card" onSubmit={add}><h2>Registrar actividad</h2><div className="form-grid"><label>Oportunidad<select value={opportunityId} onChange={e=>setOpportunityId(e.target.value)}><option value="">Sin oportunidad</option>{opps.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="call">Llamada</option><option value="meeting">Reunión</option><option value="email">Email</option><option value="whatsapp">WhatsApp</option><option value="note">Nota</option></select></label><label>Resultado / título<input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Ej. Cliente confirmó interés" /></label></div><label style={{marginTop:12}}>Detalle<textarea value={description} onChange={e=>setDescription(e.target.value)} /></label><label style={{marginTop:12,display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={completed} onChange={e=>setCompleted(e.target.checked)} /> Marcar como realizada</label><div className="section-gap"><button className="button primary">Registrar actividad</button></div></form><div className="card"><h2>Historial comercial</h2>{loading?<div className="loading">Cargando actividades…</div>:rows.map(r=><div className="timeline-item" key={r.id}><strong>{r.title}</strong><span>{r.type} · {r.opportunity_id?opportunityMap.get(r.opportunity_id)??"Oportunidad":"Sin oportunidad"} · {r.completed_at?"Realizada":"Pendiente"} · {date.format(new Date(r.completed_at??r.created_at))}</span>{r.description&&<div className="muted">{r.description}</div>}</div>)}{!loading&&rows.length===0&&<div className="empty">Sin actividades registradas.</div>}</div></div>
}
