"use client";
import {FormEvent,useEffect,useState} from "react";
import {supabase} from "@/lib/supabase";
type Choice={id:string;name?:string;display_name?:string;company_id?:string|null};
export function NewOpportunity({tenantId,stages,done}:{tenantId:string;stages:{id:string;name:string;win_probability:number;stage_type:string}[];done:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[companies,setCompanies]=useState<Choice[]>([]),[contacts,setContacts]=useState<Choice[]>([]);
 const [form,setForm]=useState({title:"",company:"",contact:"",offer:"",setup:"0",mrr:"0",months:"1",next:"",due:""});
 useEffect(()=>{if(!open)return;let alive=true;Promise.all([supabase.from("companies").select("id,name").eq("tenant_id",tenantId).order("name").limit(1000),supabase.from("contacts").select("id,display_name,company_id").eq("tenant_id",tenantId).order("display_name").limit(1000)]).then(([a,b])=>{if(!alive)return;if(a.error||b.error)setError(a.error?.message??b.error!.message);else{setCompanies(a.data??[]);setContacts(b.data??[])}});return()=>{alive=false}},[open,tenantId]);
 async function save(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");try{const stage=stages.find(s=>s.stage_type==="open");if(!stage)throw new Error("No hay una etapa abierta disponible.");const p=await supabase.from("pipeline_stages").select("pipeline_id").eq("tenant_id",tenantId).eq("id",stage.id).single();if(p.error)throw p.error;const setup=Number(form.setup),mrr=Number(form.mrr),months=Number(form.months);if(!form.title.trim()||![setup,mrr,months].every(Number.isFinite)||setup<0||mrr<0||months<1)throw new Error("Revisa el título y los importes.");const r=await supabase.from("opportunities").insert({tenant_id:tenantId,pipeline_id:p.data.pipeline_id,stage_id:stage.id,title:form.title.trim(),company_id:form.company||null,contact_id:form.contact||null,offer:form.offer.trim()||null,setup_value:setup,mrr_value:mrr,total_contract_value:setup+mrr*months,value:setup+mrr*months,currency:"DOP",probability:stage.win_probability,status:"open",next_action:form.next.trim()||null,next_action_at:form.due?new Date(form.due).toISOString():null,acquisition_source:"Manual"}).select("id").single();if(r.error)throw r.error;setOpen(false);await done()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="stack gap-16"><div><button className="button primary" onClick={()=>{setOpen(!open);setError("")}}>+ Nueva oportunidad</button></div>{open&&<form onSubmit={save} className="card stack gap-16"><h2>Nueva oportunidad comercial</h2><p className="muted">Define el importe acordado. Una oportunidad no cuenta como ingreso cobrado.</p>{error&&<div role="alert" className="notice">{error}</div>}<div className="form-grid"><label>Título<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Oferta<input placeholder="Diagnóstico, Launch, Growth…" value={form.offer} onChange={e=>setForm({...form,offer:e.target.value})}/></label><label>Empresa<select value={form.company} onChange={e=>setForm({...form,company:e.target.value,contact:""})}><option value="">Sin empresa</option>{companies.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Contacto<select value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}><option value="">Sin contacto</option>{contacts.filter(c=>!form.company||c.company_id===form.company).map(c=><option value={c.id} key={c.id}>{c.display_name}</option>)}</select></label>{([['setup','Implementación / proyecto (RD$)'],['mrr','Mensualidad (RD$)'],['months','Meses de contrato']] as const).map(([key,label])=><label key={key}>{label}<input required type="number" step={key==='months'?1:0.01} min={key==='months'?1:0} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Próxima acción<input value={form.next} onChange={e=>setForm({...form,next:e.target.value})}/></label><label>Fecha del seguimiento<input type="datetime-local" value={form.due} onChange={e=>setForm({...form,due:e.target.value})}/></label></div><div className="top-actions"><button disabled={busy} className="button primary">{busy?"Guardando…":"Crear oportunidad"}</button><button disabled={busy} type="button" className="button" onClick={()=>setOpen(false)}>Cancelar</button></div></form>}</div>
}
