import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, LockKeyhole, MapPin, Scale, ShieldCheck, Trees } from "lucide-react";
import { brokerSummary, money, property } from "@/data/cevicos";
import LeadCapture from "@/components/cevicos/LeadCapture";
import PriceCalculator from "@/components/cevicos/PriceCalculator";
import styles from "./cevicos.module.css";

export const metadata = {
  title: "812 tareas en Cevicos | Proyecto 812",
  description: "Ficha comercial digital para una propiedad de aproximadamente 812 tareas en Cevicos, Sánchez Ramírez.",
};

export default async function CevicosLandingPage({ searchParams }:{ searchParams: Promise<{ref?:string|string[]}> }) {
  const params=await searchParams; const referralCode=Array.isArray(params.ref)?params.ref[0]:params.ref;
  return <main className={styles.page}>
    <header className={styles.navWrap}><nav className={styles.nav}><Link href="/cevicos" className={styles.brand}><span className={styles.brandMark}>812</span><span>Proyecto Cevicos</span></Link><div className={styles.navActions}><Link href="#informacion" className={styles.textLink}>Información</Link><Link href="#calculator" className={styles.textLink}>Calculadora</Link><Link href="/property-sales/login" className={styles.adminLink}>Acceso brokers</Link></div></nav></header>
    <section className={styles.hero}><div className={styles.heroGlow}/><div className={styles.heroGrid}><div className={styles.heroCopy}><div className={styles.kicker}><MapPin size={16}/> Cevicos · Sánchez Ramírez</div><h1>812 tareas para <span>pensar en grande.</span></h1><p className={styles.lead}>Una propiedad de gran escala para compradores que buscan tierra, patrimonio y visión de proyecto en República Dominicana.</p><div className={styles.heroActions}><Link href="#contacto" className={styles.primaryButton}>Solicitar ficha PDF <ArrowRight size={18}/></Link><Link href="/property-sales/login" className={styles.secondaryButton}>Soy broker / Quiero venderla</Link></div><div className={styles.trustLine}><ShieldCheck size={17}/> Comercialización seria · Información sujeta a verificación documental y técnica</div></div><div className={styles.heroCard}><div className={styles.cardEyebrow}>Resumen de oportunidad</div><div className={styles.bigMetric}>{property.tasks}</div><div className={styles.metricLabel}>tareas aproximadamente</div><div className={styles.priceRow}><div><span>Precio de referencia</span><strong>{money(property.pricePerTask)}</strong><small>por tarea</small></div><div><span>Valor de referencia</span><strong>{money(property.referenceValue)}</strong><small>venta total</small></div></div><div className={styles.cardNote}><LockKeyhole size={16}/> La ubicación exacta y documentación ampliada se facilitan a interesados calificados.</div></div></div></section>
    <section id="informacion" className={styles.section}><div className={styles.sectionHeader}><span className={styles.eyebrow}>Una oportunidad de escala</span><h2>No es un solar. Es una decisión de inversión.</h2><p>La magnitud del terreno permite evaluar distintos escenarios de uso, siempre sujetos a revisión técnica, acceso, normativa y documentación final.</p></div><div className={styles.featureGrid}><article className={styles.feature}><Trees/><h3>Gran extensión</h3><p>Aproximadamente 812 tareas concentradas en una sola oportunidad comercial.</p></article><article className={styles.feature}><Scale/><h3>Precio claro</h3><p>RD$80,000 por tarea como referencia inicial, con condiciones conversables para comprador calificado.</p></article><article className={styles.feature}><BriefcaseBusiness/><h3>Enfoque de inversión</h3><p>Puede resultar de interés para inversionistas, compradores patrimoniales, productores o desarrolladores, sujeto a evaluación de uso.</p></article></div></section>
    <PriceCalculator/>
    <section id="brokers" className={styles.darkSection}><div className={styles.darkGrid}><div><span className={styles.eyebrowLight}>Red de comercialización</span><h2>Cada vendedor aprobado recibe su propio enlace.</h2><p>El sistema registra clicks, compradores y la tasa de comisión vigente al momento de captar el lead, reduciendo disputas por atribución.</p></div><div className={styles.statsGrid}><div><strong>{brokerSummary.total}</strong><span>brokers en base</span></div><div><strong>{brokerSummary.priorityA}</strong><span>prioridad A</span></div><div><strong>{brokerSummary.publicWhatsapp}</strong><span>WhatsApp públicos</span></div><div><strong>1:1</strong><span>lead ↔ corredor</span></div></div></div></section>
    <section id="contacto" className={styles.ctaSection}><div><span className={styles.eyebrow}>Siguiente paso</span><h2>Solicita la ficha comercial.</h2><p>Completa tus datos. Al enviar el formulario pasarás a una página de confirmación con acceso inmediato al PDF. Si llegaste mediante un corredor autorizado, tu solicitud se registrará con su código de atribución.</p></div><LeadCapture referralCode={referralCode}/></section>
    <footer className={styles.footer}><div>Proyecto 812 · Cevicos, Sánchez Ramírez</div><div>Ficha preliminar · Sujeta a verificación documental, técnica y legal.</div></footer>
  </main>;
}
