create extension if not exists pgcrypto with schema extensions;

create table if not exists public.land_sales_profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  role text not null default 'seller' check (role in ('admin','seller')),
  status text not null default 'pending' check (status in ('pending','active','suspended','rejected')),
  full_name text not null,
  company text,
  phone text,
  referral_code text not null unique,
  commission_rate numeric(5,2) not null default 0 check (commission_rate >= 0 and commission_rate <= 100),
  terms_version text,
  terms_accepted_at timestamptz,
  approved_at timestamptz,
  approved_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.land_sales_leads (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid references public.land_sales_profiles(id),
  referral_code text,
  commission_rate_snapshot numeric(5,2) not null default 0,
  buyer_name text not null,
  buyer_phone text not null,
  buyer_email text,
  buyer_company text,
  desired_use text,
  budget text,
  notes text,
  stage text not null default 'new' check (stage in ('new','qualified','contacted','visit','offer','negotiation','closed_won','closed_lost')),
  source_url text,
  attribution_locked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.land_sales_clicks (
  id bigint generated by default as identity primary key,
  seller_id uuid references public.land_sales_profiles(id),
  referral_code text,
  session_id text,
  source_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.land_sales_commissions (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null unique references public.land_sales_leads(id) on delete cascade,
  seller_id uuid not null references public.land_sales_profiles(id),
  commission_rate numeric(5,2) not null,
  sale_price numeric(18,2) not null default 0 check (sale_price >= 0),
  commission_amount numeric(18,2) generated always as (round(sale_price * commission_rate / 100.0, 2)) stored,
  status text not null default 'pending' check (status in ('pending','approved','payable','paid','disputed','cancelled')),
  paid_at timestamptz,
  payment_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.land_sales_audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id),
  entity_type text not null,
  entity_id text not null,
  action text not null,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists land_sales_profiles_status_idx on public.land_sales_profiles(status, role);
create index if not exists land_sales_leads_seller_idx on public.land_sales_leads(seller_id, created_at desc);
create index if not exists land_sales_leads_stage_idx on public.land_sales_leads(stage, created_at desc);
create index if not exists land_sales_clicks_seller_idx on public.land_sales_clicks(seller_id, created_at desc);
create index if not exists land_sales_commissions_seller_idx on public.land_sales_commissions(seller_id, status);

create or replace function private.is_land_sales_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(
    encode(extensions.digest(lower(coalesce(auth.jwt() ->> 'email','')), 'sha256'), 'hex') = any(array[
      'de28264ea4b7e958e8b857968ec0220b133e8bcd33c1a7d90b54799c1baf5f42',
      '158012855230d0652f82b64502f1f586cb5b877875805efd5ba750cc2952c191'
    ]), false
  )
  or exists (
    select 1 from public.land_sales_profiles p
    where p.auth_user_id = auth.uid() and p.role = 'admin' and p.status = 'active'
  );
$$;

create or replace function public.ensure_land_admin_profile()
returns public.land_sales_profiles
language plpgsql
security definer
set search_path = ''
as $$
declare v_profile public.land_sales_profiles;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if not private.is_land_sales_admin() then raise exception 'not authorized'; end if;

  insert into public.land_sales_profiles(auth_user_id, role, status, full_name, referral_code, commission_rate, approved_at, approved_by)
  values (
    auth.uid(), 'admin', 'active', coalesce(auth.jwt() ->> 'email','Administrador'),
    'ADM-' || upper(substr(md5(auth.uid()::text), 1, 8)), 0, now(), auth.uid()
  )
  on conflict (auth_user_id) do update
    set role='admin', status='active', approved_at=coalesce(public.land_sales_profiles.approved_at, now()), updated_at=now()
  returning * into v_profile;

  return v_profile;
end;
$$;

create or replace function public.register_land_seller(
  p_full_name text,
  p_company text default null,
  p_phone text default null,
  p_accept_terms boolean default false
)
returns public.land_sales_profiles
language plpgsql
security definer
set search_path = ''
as $$
declare v_profile public.land_sales_profiles;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if not p_accept_terms then raise exception 'terms must be accepted'; end if;
  if nullif(trim(p_full_name),'') is null then raise exception 'full name required'; end if;

  insert into public.land_sales_profiles(
    auth_user_id, role, status, full_name, company, phone, referral_code, commission_rate, terms_version, terms_accepted_at
  ) values (
    auth.uid(), 'seller', 'pending', trim(p_full_name), nullif(trim(p_company),''), nullif(trim(p_phone),''),
    '812-' || upper(substr(md5(auth.uid()::text || clock_timestamp()::text), 1, 10)),
    0, '2026-09-v1', now()
  )
  on conflict (auth_user_id) do update
    set full_name=excluded.full_name, company=excluded.company, phone=excluded.phone,
        terms_version=excluded.terms_version, terms_accepted_at=excluded.terms_accepted_at, updated_at=now()
  returning * into v_profile;

  return v_profile;
end;
$$;

create or replace function public.register_land_lead(
  p_referral_code text,
  p_buyer_name text,
  p_buyer_phone text,
  p_buyer_email text default null,
  p_buyer_company text default null,
  p_desired_use text default null,
  p_budget text default null,
  p_notes text default null,
  p_source_url text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare v_seller public.land_sales_profiles; v_id uuid;
begin
  if nullif(trim(p_buyer_name),'') is null or nullif(trim(p_buyer_phone),'') is null then
    raise exception 'name and phone required';
  end if;

  if nullif(trim(coalesce(p_referral_code,'')),'') is not null then
    select * into v_seller from public.land_sales_profiles
    where referral_code = upper(trim(p_referral_code)) and role='seller' and status='active';
    if v_seller.id is null then raise exception 'referral code is not active'; end if;
  end if;

  insert into public.land_sales_leads(
    seller_id, referral_code, commission_rate_snapshot, buyer_name, buyer_phone, buyer_email,
    buyer_company, desired_use, budget, notes, source_url
  ) values (
    v_seller.id, case when v_seller.id is null then null else v_seller.referral_code end,
    coalesce(v_seller.commission_rate,0), trim(p_buyer_name), trim(p_buyer_phone),
    nullif(trim(p_buyer_email),''), nullif(trim(p_buyer_company),''), nullif(trim(p_desired_use),''),
    nullif(trim(p_budget),''), nullif(trim(p_notes),''), nullif(trim(p_source_url),'')
  ) returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.track_land_sales_click(
  p_referral_code text,
  p_session_id text default null,
  p_source_url text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare v_seller public.land_sales_profiles; v_id bigint;
begin
  if nullif(trim(coalesce(p_referral_code,'')),'') is null then return null; end if;
  select * into v_seller from public.land_sales_profiles
  where referral_code = upper(trim(p_referral_code)) and role='seller' and status='active';
  if v_seller.id is null then return null; end if;

  insert into public.land_sales_clicks(seller_id, referral_code, session_id, source_url)
  values(v_seller.id, v_seller.referral_code, nullif(trim(p_session_id),''), nullif(trim(p_source_url),''))
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function private.protect_land_lead_attribution()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if (new.seller_id is distinct from old.seller_id or new.referral_code is distinct from old.referral_code or new.commission_rate_snapshot is distinct from old.commission_rate_snapshot) then
    if not private.is_land_sales_admin() then raise exception 'lead attribution is locked'; end if;
    insert into public.land_sales_audit_events(actor_user_id, entity_type, entity_id, action, old_data, new_data)
    values(auth.uid(), 'lead', old.id::text, 'attribution_changed', to_jsonb(old), to_jsonb(new));
  end if;
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists land_sales_lead_attribution_guard on public.land_sales_leads;
create trigger land_sales_lead_attribution_guard
before update on public.land_sales_leads
for each row execute function private.protect_land_lead_attribution();

alter table public.land_sales_profiles enable row level security;
alter table public.land_sales_leads enable row level security;
alter table public.land_sales_clicks enable row level security;
alter table public.land_sales_commissions enable row level security;
alter table public.land_sales_audit_events enable row level security;

drop policy if exists land_profiles_admin_all on public.land_sales_profiles;
create policy land_profiles_admin_all on public.land_sales_profiles for all to authenticated
using (private.is_land_sales_admin()) with check (private.is_land_sales_admin());
drop policy if exists land_profiles_self_read on public.land_sales_profiles;
create policy land_profiles_self_read on public.land_sales_profiles for select to authenticated
using (auth_user_id = auth.uid());

drop policy if exists land_leads_admin_all on public.land_sales_leads;
create policy land_leads_admin_all on public.land_sales_leads for all to authenticated
using (private.is_land_sales_admin()) with check (private.is_land_sales_admin());
drop policy if exists land_leads_seller_read on public.land_sales_leads;
create policy land_leads_seller_read on public.land_sales_leads for select to authenticated
using (seller_id in (select p.id from public.land_sales_profiles p where p.auth_user_id = auth.uid()));

drop policy if exists land_clicks_admin_read on public.land_sales_clicks;
create policy land_clicks_admin_read on public.land_sales_clicks for select to authenticated
using (private.is_land_sales_admin());
drop policy if exists land_clicks_seller_read on public.land_sales_clicks;
create policy land_clicks_seller_read on public.land_sales_clicks for select to authenticated
using (seller_id in (select p.id from public.land_sales_profiles p where p.auth_user_id = auth.uid()));

drop policy if exists land_commissions_admin_all on public.land_sales_commissions;
create policy land_commissions_admin_all on public.land_sales_commissions for all to authenticated
using (private.is_land_sales_admin()) with check (private.is_land_sales_admin());
drop policy if exists land_commissions_seller_read on public.land_sales_commissions;
create policy land_commissions_seller_read on public.land_sales_commissions for select to authenticated
using (seller_id in (select p.id from public.land_sales_profiles p where p.auth_user_id = auth.uid()));

drop policy if exists land_audit_admin_read on public.land_sales_audit_events;
create policy land_audit_admin_read on public.land_sales_audit_events for select to authenticated
using (private.is_land_sales_admin());

revoke all on public.land_sales_profiles, public.land_sales_leads, public.land_sales_clicks, public.land_sales_commissions, public.land_sales_audit_events from anon;
grant select on public.land_sales_profiles, public.land_sales_leads, public.land_sales_clicks, public.land_sales_commissions to authenticated;
grant update on public.land_sales_profiles, public.land_sales_leads, public.land_sales_commissions to authenticated;
grant select on public.land_sales_audit_events to authenticated;

revoke all on function public.ensure_land_admin_profile() from public, anon;
revoke all on function public.register_land_seller(text,text,text,boolean) from public, anon;
grant execute on function public.ensure_land_admin_profile() to authenticated;
grant execute on function public.register_land_seller(text,text,text,boolean) to authenticated;
grant execute on function public.register_land_lead(text,text,text,text,text,text,text,text,text) to anon, authenticated;
grant execute on function public.track_land_sales_click(text,text,text) to anon, authenticated;
